/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zouhaib mahamoud
 */
public class AccueilDemineur extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccueilDemineur.class.getName());

    public AccueilDemineur() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bouton_commencer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        combo_niveau = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Jeu du Démineur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 107, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bienvenue dans le jeu du Démineur.\nCliquez sur Commencer pour lancer une partie.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 300, -1));

        bouton_commencer.setText("Commencer");
        bouton_commencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_commencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_commencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel2.setText("Niveau: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        combo_niveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facile", "Normal", "Difficle", "" }));
        getContentPane().add(combo_niveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_commencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_commencerActionPerformed
                                    

        String niveau = combo_niveau.getSelectedItem().toString();
        int lignes;
        int colonnes;
        int bombes;

        if (niveau.equals("Facile")) {
            lignes = 8;
            colonnes = 8;
            bombes = 10;
        } else if (niveau.equals("Moyen")) {
            lignes = 10;
            colonnes = 10;
            bombes = 15;
        } else { // Difficile
            lignes = 12;
            colonnes = 12;
            bombes = 25;
        }

        // Ouvre la fenêtre de jeu avec ces paramètres
        interface_graphique fenetreJeu = new interface_graphique(lignes, colonnes, bombes);
        fenetreJeu.setVisible(true);

        // Ferme l'écran d'accueil
        this.dispose();

    }//GEN-LAST:event_bouton_commencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilDemineur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_commencer;
    private javax.swing.JComboBox<String> combo_niveau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
