/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JButton;
import java.awt.GridLayout;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author chalu
 */
public class interface_graphique extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interface_graphique.class.getName());
private GrilleDeJeu grille;
private JButton[][] boutons;

private int nbLignes = 10;
private int nbColonnes = 10;
private int nbBombes = 15;

    /**
     * Creates new form interface_graphique
     */
public interface_graphique() {
    initComponents();
}
private void initialiserJeu() {

    grille = new GrilleDeJeu(nbLignes, nbColonnes, nbBombes);
    grille.placerBombesAleatoirement();
    grille.calculerBombesAdjacentes();

    PanneauGrille.removeAll();
    PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));

    boutons = new JButton[nbLignes][nbColonnes];

    for (int i = 0; i < nbLignes; i++) {
        for (int j = 0; j < nbColonnes; j++) {

            JButton bouton = new JButton("?");
            bouton.setFont(new Font("Arial", Font.BOLD, 16));

            final int ligne = i;
            final int colonne = j;

            bouton.addActionListener(e -> clicCellule(ligne, colonne));

            boutons[i][j] = bouton;
            PanneauGrille.add(bouton);
        }
    }

    PanneauGrille.revalidate();
    PanneauGrille.repaint();
}
private void clicCellule(int ligne, int colonne) {

    grille.revelerCellule(ligne, colonne);
    mettreAJourAffichage();

    if (grille.getPresenceBombe(ligne, colonne)) {
        JOptionPane.showMessageDialog(this, " Bombe ! Partie perdue");
        afficherToutesLesBombes();
    } 
    else if (grille.toutesCellulesRevelees()) {
        JOptionPane.showMessageDialog(this, " Victoire !");
    }
}
private void mettreAJourAffichage() {
    for (int i = 0; i < nbLignes; i++) {
        for (int j = 0; j < nbColonnes; j++) {
            String val = grille.getAffichageCellule(i, j);
            boutons[i][j].setText(val);
            boutons[i][j].setEnabled(val.equals("?"));
        }
    }
}


private void afficherToutesLesBombes() {

    for (int i = 0; i < nbLignes; i++) {
        for (int j = 0; j < nbColonnes; j++) {

            if (grille.getPresenceBombe(i, j)) {
                boutons[i][j].setText("B");
            }
            boutons[i][j].setEnabled(false);
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bouton_commencer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanneauGrille = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bouton_commencer.setText("Commencer");
        bouton_commencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_commencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_commencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jLabel1.setText("Score Maximum");
        jPanel1.add(jLabel1);

        jLabel2.setText("Jeu du Démineur");
        jPanel1.add(jLabel2);

        jLabel3.setText("nombre");
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 540, -1));

        PanneauGrille.setBackground(new java.awt.Color(150, 242, 242));
        PanneauGrille.setLayout(new java.awt.GridLayout(10, 10));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 470, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_commencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_commencerActionPerformed
initialiserJeu();
    }//GEN-LAST:event_bouton_commencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interface_graphique().setVisible(true));
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton bouton_commencer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
